version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: always
    networks:
      - inception-network
    volumes:
      -  web-data:/var/www/wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    restart: always
    networks:
      - inception-network
    volumes:
      -  web-data:/var/www/wordpress
    env_file:
      - ./.env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    restart: always
    networks:
      - inception-network
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./.env

volumes:
  web-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jpeyron/data/web-data'
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jpeyron/data/db-data'

networks:
  inception-network: