version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - web-data:/var/www/html
    depends_on:
      - wordpress
    env_file: .env
    networks:
      - inception-network 
  
  database:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env
    networks:
      - inception-network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    restart: always
    volumes:
      - web-data:/var/www/html
    depends_on:
      - database
    env_file: .env
    networks:
      - inception-network

volumes:
  web-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jpeyron/data/web-data'
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jpeyron/data/db-data'

networks:
  inception-network: