services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    restart: always
    volumes:
      - web-data:/var/wwww/wordpress
    env_file: .env
    networks:
      - inception_network
  
  database:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    restart: always
    volumes:
      - web-data:/var/www/wordpress
    env_file: .env
    networks:
      - inception_network

volumes:
  web-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jpeyron/data/web-data'
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jpeyron/data/db-data'

networks:
  inception_network:
    driver: bridge